### ISSUE TITLE
本地部署报错，无法生成，貌似无法使用cuda导致

### ISSUE THREAD

**Issue by alex9441** [lenML/ChatTTS-Forge#1]
前端可以启动，点击生成报‘Error’
日志输出
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
ERROR:modules.ssml:apply style failed, Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
INFO:modules.ssml:collect len(segments): 1
DEBUG:matplotlib.pyplot:Loaded backend QtAgg version 5.15.10.
看起来是无法使用cuda加速导致的。我计算机应该没问题，另外两个同样基于ChatTTS的webUI都可以运行。

**Comment by handles98** [comment]
我这里可以正常生成，是不是没安装GPU版的torch?安装试下，cu118后面换成你系统的CUDA版本号
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by alex9441** [comment]
从新CONDA了虚拟环境，程序莫名其妙的跑起来了。。。。
好吧。
谨祝作者码运昌隆！
